name: Build Release APKs

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    name: Build APKs on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle Cache
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Extract Version Name
        # Finds 'versionName = "X.X.X"' in your gradle file
        run: |
          VERSION=$(grep -oP 'versionName\s*=\s*"\K[^"]+' app/build.gradle.kts)
          echo "VERSION_NAME=$VERSION" >> $GITHUB_ENV

      - name: Build Both Release Flavors
        run: ./gradlew assembleFdroidRelease assembleGithubRelease

      - name: Sign F-Droid APK
        uses: r0adkll/sign-android-release@v1
        id: sign_fdroid
        with:
          releaseDirectory: app/build/outputs/apk/fdroid/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Sign GitHub APK
        uses: r0adkll/sign-android-release@v1
        id: sign_github
        with:
          releaseDirectory: app/build/outputs/apk/github/release
          signingKeyBase64: ${{ secrets.KEYSTORE_BASE64 }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: '34.0.0'

      - name: Rename the Signed APKs
        run: |
          mv app/build/outputs/apk/fdroid/release/*-signed.apk SoundPod-v${{ env.VERSION_NAME }}-fdroid-release.apk
          mv app/build/outputs/apk/github/release/*-signed.apk SoundPod-v${{ env.VERSION_NAME }}-github-release.apk

      - name: Upload APKs as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: SoundPod-v${{ env.VERSION_NAME }}-Releases
          path: |
            SoundPod-v${{ env.VERSION_NAME }}-fdroid-release.apk
            SoundPod-v${{ env.VERSION_NAME }}-github-release.apk
